<?php
/**
 * @file
 */


/**
 * Implementation of hook_menu
 */
function events_admin_menu() {

  // Panels pane layout enable/disable page callback
  $items['admin/events/test'] = array(
    'type' => MENU_CALLBACK,
    //'page callback' => 'panopoly_admin_switch_layout_action',
    //'page arguments' => array(4, 5, 6),
    //'access callback' => 'panopoly_admin_panels_layout_access',
  );

  // Add a local action link for the flexible layout builder
  
  $items['admin/events/admin/conference/sessions'] = array(
    'title' => 'Administer Session Proposals and Scheduling',
    'description' => 'Session Administration',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/conference/sessions/accepted'),
    'type' => MENU_LOCAL_ACTION,
    'access arguments' => array('administer page manager'),
  );

  $items['admin/events/admin/conference/contact-speakers'] = array(
    'title' => 'Contact Speakers',
    'description' => 'Contct Session Speakers',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/conference/contact-speakers/'),
    'type' => MENU_LOCAL_ACTION,
    'access arguments' => array('administer page manager'),
  );
  

  // Add an administration page for Panopoly
  $items['admin/events'] = array(
    'title' => 'Events',
    'description' => 'Administer all things Events.',
    'weight' => -8,
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  // Add an administration section for Panopoly settings
  /*
  $items['admin/panopoly/settings'] = array(
    'title' => 'Panopoly Settings',
    'description' => 'Configuration related to Panopoly',
    'weight' => 50,
    'position' => 'left',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  */

  return $items;
}

/**
 * Implementation of hook_menu_alter()
 */
function events_admin_menu_alter(&$items) {

  // Set the description of the page library
  $items['admin/events/test']['description'] = 'This is the page library for the site. See your landing pages, page templates, and overriden page templates.';

}
